version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root
  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
